name: API Trigger Every 15 Minutes

on:
  schedule:
    - cron: "*/15 * * * *" 

jobs:
  trigger-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: |
          curl -X GET https://tunestats.vercel.app/api/updatePoints
